//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Input/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""PlayerControls"",
            ""id"": ""15de25fd-3493-45aa-83d8-e23f60f20a97"",
            ""actions"": [
                {
                    ""name"": ""MovementVertical"",
                    ""type"": ""Button"",
                    ""id"": ""4f7b7385-6afa-4010-a2c4-86bcebafd796"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MovementHorizontal"",
                    ""type"": ""Button"",
                    ""id"": ""25d88db7-611d-4ac9-9baa-2c98a084d429"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpaceBar"",
                    ""type"": ""Button"",
                    ""id"": ""8413185a-c532-4d6f-a2d2-c6d0a5b0dea2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""c582fa1e-078b-44f9-809a-3f134120ee0d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenCustomize"",
                    ""type"": ""Button"",
                    ""id"": ""531b968a-f02c-492e-979c-0ff0689a7370"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""20c36bfe-7c0e-4df1-bebd-b48b9331b5cb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftFirePress"",
                    ""type"": ""Button"",
                    ""id"": ""94471ccb-36df-496c-b021-af47736f23a7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightFirePress"",
                    ""type"": ""Button"",
                    ""id"": ""586a9141-1420-4266-80d6-c351be7506c8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftFireRelease"",
                    ""type"": ""Button"",
                    ""id"": ""ad426eb4-e87e-4a4a-8669-e1a3555ffcd1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightFireRelease"",
                    ""type"": ""Button"",
                    ""id"": ""224b758c-e3d1-45b5-a119-18770d69c7a2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Vertical"",
                    ""id"": ""e671ab16-baf3-4198-a881-9f15476d5cbe"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementVertical"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""e89a075d-73c6-49c2-89d9-d9b836b6ea6f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MovementVertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""42d06081-0d27-4696-a4fb-2edc5b86aa7e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MovementVertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c6b34b88-0553-4b5f-88bb-fc6fd1073a3a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""SpaceBar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Horizontal"",
                    ""id"": ""d624a503-b30c-4abf-bd9e-0f7ab635fcfd"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementHorizontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""30345cd8-ee12-4b21-aa15-e534d6bba508"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MovementHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""71a0f6a3-1219-47f1-bd75-0567dc914f25"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MovementHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c5c46841-bb91-4c8c-bab6-d840080bc81b"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03fb64bb-ad59-4d18-a2f7-47e070aa5963"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""OpenCustomize"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""adc08988-a3d0-4a41-8d99-875a27851da8"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""115be00a-9d32-4d01-835b-8ec18ab781c8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""LeftFirePress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92c025c2-c0e7-4198-b589-9f85b106a3b2"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""RightFirePress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68381fe9-b9e4-4de0-aeb4-7556d10d4ee7"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""LeftFireRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7dec4efb-e392-4c8d-907c-ba21502b9eb4"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""RightFireRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PlayerControls
        m_PlayerControls = asset.FindActionMap("PlayerControls", throwIfNotFound: true);
        m_PlayerControls_MovementVertical = m_PlayerControls.FindAction("MovementVertical", throwIfNotFound: true);
        m_PlayerControls_MovementHorizontal = m_PlayerControls.FindAction("MovementHorizontal", throwIfNotFound: true);
        m_PlayerControls_SpaceBar = m_PlayerControls.FindAction("SpaceBar", throwIfNotFound: true);
        m_PlayerControls_Interact = m_PlayerControls.FindAction("Interact", throwIfNotFound: true);
        m_PlayerControls_OpenCustomize = m_PlayerControls.FindAction("OpenCustomize", throwIfNotFound: true);
        m_PlayerControls_Pause = m_PlayerControls.FindAction("Pause", throwIfNotFound: true);
        m_PlayerControls_LeftFirePress = m_PlayerControls.FindAction("LeftFirePress", throwIfNotFound: true);
        m_PlayerControls_RightFirePress = m_PlayerControls.FindAction("RightFirePress", throwIfNotFound: true);
        m_PlayerControls_LeftFireRelease = m_PlayerControls.FindAction("LeftFireRelease", throwIfNotFound: true);
        m_PlayerControls_RightFireRelease = m_PlayerControls.FindAction("RightFireRelease", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerControls
    private readonly InputActionMap m_PlayerControls;
    private IPlayerControlsActions m_PlayerControlsActionsCallbackInterface;
    private readonly InputAction m_PlayerControls_MovementVertical;
    private readonly InputAction m_PlayerControls_MovementHorizontal;
    private readonly InputAction m_PlayerControls_SpaceBar;
    private readonly InputAction m_PlayerControls_Interact;
    private readonly InputAction m_PlayerControls_OpenCustomize;
    private readonly InputAction m_PlayerControls_Pause;
    private readonly InputAction m_PlayerControls_LeftFirePress;
    private readonly InputAction m_PlayerControls_RightFirePress;
    private readonly InputAction m_PlayerControls_LeftFireRelease;
    private readonly InputAction m_PlayerControls_RightFireRelease;
    public struct PlayerControlsActions
    {
        private @Controls m_Wrapper;
        public PlayerControlsActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MovementVertical => m_Wrapper.m_PlayerControls_MovementVertical;
        public InputAction @MovementHorizontal => m_Wrapper.m_PlayerControls_MovementHorizontal;
        public InputAction @SpaceBar => m_Wrapper.m_PlayerControls_SpaceBar;
        public InputAction @Interact => m_Wrapper.m_PlayerControls_Interact;
        public InputAction @OpenCustomize => m_Wrapper.m_PlayerControls_OpenCustomize;
        public InputAction @Pause => m_Wrapper.m_PlayerControls_Pause;
        public InputAction @LeftFirePress => m_Wrapper.m_PlayerControls_LeftFirePress;
        public InputAction @RightFirePress => m_Wrapper.m_PlayerControls_RightFirePress;
        public InputAction @LeftFireRelease => m_Wrapper.m_PlayerControls_LeftFireRelease;
        public InputAction @RightFireRelease => m_Wrapper.m_PlayerControls_RightFireRelease;
        public InputActionMap Get() { return m_Wrapper.m_PlayerControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerControlsActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerControlsActions instance)
        {
            if (m_Wrapper.m_PlayerControlsActionsCallbackInterface != null)
            {
                @MovementVertical.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnMovementVertical;
                @MovementVertical.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnMovementVertical;
                @MovementVertical.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnMovementVertical;
                @MovementHorizontal.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnMovementHorizontal;
                @MovementHorizontal.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnMovementHorizontal;
                @MovementHorizontal.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnMovementHorizontal;
                @SpaceBar.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnSpaceBar;
                @SpaceBar.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnSpaceBar;
                @SpaceBar.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnSpaceBar;
                @Interact.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnInteract;
                @OpenCustomize.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnOpenCustomize;
                @OpenCustomize.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnOpenCustomize;
                @OpenCustomize.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnOpenCustomize;
                @Pause.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnPause;
                @LeftFirePress.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnLeftFirePress;
                @LeftFirePress.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnLeftFirePress;
                @LeftFirePress.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnLeftFirePress;
                @RightFirePress.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnRightFirePress;
                @RightFirePress.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnRightFirePress;
                @RightFirePress.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnRightFirePress;
                @LeftFireRelease.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnLeftFireRelease;
                @LeftFireRelease.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnLeftFireRelease;
                @LeftFireRelease.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnLeftFireRelease;
                @RightFireRelease.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnRightFireRelease;
                @RightFireRelease.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnRightFireRelease;
                @RightFireRelease.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnRightFireRelease;
            }
            m_Wrapper.m_PlayerControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MovementVertical.started += instance.OnMovementVertical;
                @MovementVertical.performed += instance.OnMovementVertical;
                @MovementVertical.canceled += instance.OnMovementVertical;
                @MovementHorizontal.started += instance.OnMovementHorizontal;
                @MovementHorizontal.performed += instance.OnMovementHorizontal;
                @MovementHorizontal.canceled += instance.OnMovementHorizontal;
                @SpaceBar.started += instance.OnSpaceBar;
                @SpaceBar.performed += instance.OnSpaceBar;
                @SpaceBar.canceled += instance.OnSpaceBar;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @OpenCustomize.started += instance.OnOpenCustomize;
                @OpenCustomize.performed += instance.OnOpenCustomize;
                @OpenCustomize.canceled += instance.OnOpenCustomize;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @LeftFirePress.started += instance.OnLeftFirePress;
                @LeftFirePress.performed += instance.OnLeftFirePress;
                @LeftFirePress.canceled += instance.OnLeftFirePress;
                @RightFirePress.started += instance.OnRightFirePress;
                @RightFirePress.performed += instance.OnRightFirePress;
                @RightFirePress.canceled += instance.OnRightFirePress;
                @LeftFireRelease.started += instance.OnLeftFireRelease;
                @LeftFireRelease.performed += instance.OnLeftFireRelease;
                @LeftFireRelease.canceled += instance.OnLeftFireRelease;
                @RightFireRelease.started += instance.OnRightFireRelease;
                @RightFireRelease.performed += instance.OnRightFireRelease;
                @RightFireRelease.canceled += instance.OnRightFireRelease;
            }
        }
    }
    public PlayerControlsActions @PlayerControls => new PlayerControlsActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface IPlayerControlsActions
    {
        void OnMovementVertical(InputAction.CallbackContext context);
        void OnMovementHorizontal(InputAction.CallbackContext context);
        void OnSpaceBar(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnOpenCustomize(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnLeftFirePress(InputAction.CallbackContext context);
        void OnRightFirePress(InputAction.CallbackContext context);
        void OnLeftFireRelease(InputAction.CallbackContext context);
        void OnRightFireRelease(InputAction.CallbackContext context);
    }
}
